site_name: InTheCloudDan's Corner
site_url: https://intheclouddan.github.io/blog/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - blog:
      enabled: !ENV CI
      blog_toc: true
      blog_dir: "posts"
      post_dir: "posts/entries"
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "posts/.authors.yml"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/intheclouddan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/intheclouddan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/danielobrien123/

nav:
  - Home: 'index.md'
  - Posts: 
    - posts/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/intheclouddan"  target="_blank" rel="noopener">Dan O'Brien</a>