authors:
  intheclouddan:
    name: Dan O'Brien
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10308834?v=4
    url: https://twitter.com/intent/follow?screen_name=intheclouddan